### ISSUE TITLE
Missing `nil` handling on `mark_as_completed`

### ISSUE THREAD

**Issue by FrancisMurilloDigix** [otobus/event_bus#113]
**Describe the bug**
During a day or two in production, an error occurs at `mark_as_completed` where `fetch` becomes `nil`. Based on the snippet below:

```elixir
  @doc false
  @spec mark_as_completed(subscriber_with_event_ref()) :: :ok
  def mark_as_completed({subscriber, event_shadow}) do
    {subscribers, completers, skippers} = fetch(event_shadow)   # Does not handle `nil` 
    save_or_delete(event_shadow, {subscribers, [subscriber | completers], skippers})
  end

  @doc false
  @spec fetch(event_shadow()) :: any()
  def fetch({topic, id}) do
    case Ets.lookup(table_name(topic), id) do
      [{_, data}] -> data
      _ -> nil
    end
  end
```

A guard clause for `nil` can be put here to prevent the application from crashing.

**To Reproduce**
1. Release an application with `:event_bus` in FreeBSD
2. Wait for a day or two
3. Application crashes and stops because of `mark_as_completed`

**Expected behavior**
Despite ETS data loss, application should safely handle errors and not crash the application

**Logs**
```
No logs
```

 - OS: FreeBSD 11.2
 - Elixir version: 1.9.0
 - OTP version: 21.0

**Comment by mustafaturan** [comment]
Thanks for reporting @FrancisMurilloDigix, I will be considering the `nil` handling. Currently, I am not 100% sure about how to report error. I will check other public repos for related issues. If you have any suggestions beside the logging that error case, please do not hesitate to share. So, people can aware of ETS crashed and got `nil`.  Since this is only mark_as_completed/skipped case, it seems good to go with logging at start. Would you like to create a PR?

**Comment by mustafaturan** [comment]
```elixir
  @spec fetch(event_shadow()) :: any()
  def fetch({topic, id}) do
    case Ets.lookup(table_name(topic), id) do
      [{_, data}] -> data
      reason ->
        # Log here the reason
        Logger.log(:info, fn -> "[EVENTBUS]\s#{topic}.#{id}:\s#{inspect(reason)}" end)
        {[],[],[]}
    end
  end
```

**Comment by mustafaturan** [comment]
And the spec could be re-written as:
```
@spec fetch(event_shadow()) :: {list(), list(), list()}
```

**Comment by FrancisMurilloDigix** [comment]
Okay, I'll have it done by the day.

**Comment by FrancisMurilloDigix** [comment]
Just to confirm, [Ets.lookup/2](http://erlang.org/doc/man/ets.html#lookup-2) returns an array of tuples. So the case handling should be:

```elixir
  case Ets.lookup(table_name(topic), id) do
      [{_, data}] -> data
      [] ->
        {[],[],[]}
    end
```

So `reason` is an empty value. I think we can log reason as an `:ets_error` or something.

**Comment by mustafaturan** [comment]
Thanks you @FrancisMurilloDigix , I am going to bump the patch version today.
