### ISSUE TITLE
Are there any plans to decouple event store from event bus? 

### ISSUE THREAD

**Issue by lessless** [otobus/event_bus#174]
Hi,

Are there any plans to decouple event store from event bus? Those are two different things really and there should be enough cases for using Event Bus as it is in this library and external event store.

Thanks.

**Comment by mustafaturan** [comment]
Hi @lessless , I don't have plan for separation of event store but adding new event store is possible in an event driven way. Checkout the sample project https://github.com/otobus/event_bus_postgres.

**Comment by lessless** [comment]
@mustafaturan thanks for reply. What I mean - I'd rather have an event bus without an event store, or with a transient event store.

**Comment by mustafaturan** [comment]
Please feel free to fork, there could be many others interested in too. It is MIT license ;)
