### ISSUE TITLE
Sample Listener Implementation

### ISSUE THREAD

**Issue by jodyalbritton** [otobus/event_bus#22]
Do you have a more complete example of a listener?  At the top of the example is ...
Are you doing "use GenServer"?

Does your dialyzer report show that handle_cast has no return?

It would be helpful to have a full working implementation as an example. So far I have used EventBus.nofity(event) and then I was able to look up the event, but nothing in my handle_cast function is being done. I placed an IO.inspect handle_cast and nothing is output. 

any ideas?

**Comment by mustafaturan** [comment]
Hey @jodyalbritton 

For sample implementations you can check: 

1) https://github.com/mustafaturan/messenger_bot
2) https://github.com/otobus/event_bus_postgres (with GenStage)

**Comment by jodyalbritton** [comment]
Thanks! I found what I was looking for.
