### ISSUE TITLE
Change Time Format to UTC and avoid time shifting issues.

### ISSUE THREAD

**Issue by jodyalbritton** [otobus/event_bus#23]
The current implementation uses System.os_time which can vary depending on locale and daylight savings time. It also returns a time_unit :: integer rather than straight int which breaks a contract and makes dialyzer complain. The better alternative is to use the DateTime module. 

```Elixir
DateTime.utc_now |> DateTime.to_unix(:microseconds)
```

**Comment by mustafaturan** [comment]
Hi @jodyalbritton 

According to the doc System.os_time/1 returns integer(https://hexdocs.pm/elixir/System.html#os_time/1). And since it is returning Unix timestamp it shouldn't affect daylight saving time. But I agree both(System.os_time/1 and DateTime.utc_now/0 depends local time.
