### ISSUE TITLE
Broken Contract

### ISSUE THREAD

**Issue by jodyalbritton** [otobus/event_bus#50]
``` elixir
The call:
EventBus.subscribe(
  {Core.Topics.Handler,
   [
     :topic1,
     :topic2,
     :topic3,
     :topic4,
     ...
   ]}
)

breaks the contract
(listener_with_topic_patterns()) :: :ok
```

Getting dialyzer errrors when I try to subsribe to some topics. Any ideas?

**Comment by mustafaturan** [comment]
Hey @jodyalbritton 

It seems it is not an issue. Feel free to ask questions on stackoverflow with the #elixir-eventbus tag. And then ping me on twitter `@mustafaturan` handle.

Topic patterns can only be string representation of regex patterns, you can use like below:

```elixir
EventBus.subscribe(
  {Core.Topics.Handler,
   [
     "^topic1$",
     "^topic2$",
     ...
   ]}
)
```

For more details please refer to [`topic_pattern`](https://hexdocs.pm/event_bus/EventBus.html#t:topic_pattern/0), [`topic_pattern_list`](https://hexdocs.pm/event_bus/EventBus.html#t:topic_pattern_list/0), [`listener_with_topic_patterns`](https://hexdocs.pm/event_bus/EventBus.html#t:listener_with_topic_patterns/0) type spec documentations
