### ISSUE TITLE
Dialyzer errors involving @eb_time_unit

### ISSUE THREAD

**Issue by ShaneWilton** [otobus/event_bus#52]
`@eb_time_unit` defaults to `:micro_seconds`, but the Elixir typespecs only specify `:microseconds` as a valid value (even though both work). This leads to Dialyzer errors when notifying to a topic:

```
The call:
System.monotonic_time(:micro_seconds)

breaks the contract
(time_unit()) :: integer()
```

**Comment by ShaneWilton** [comment]
From the Elixir docs:

> Keep in mind the Erlang API prior to version 19.1 will use :milli_seconds, :micro_seconds and :nano_seconds as time units although Elixir normalizes their spelling to match the SI convention.

**Comment by mustafaturan** [comment]
Thanks @ShaneWilton , I added my comments to the PR

**Comment by ShaneWilton** [comment]
Alright, I finally had a chance to look into this. Looks like Erlang 19+ standardized on singular names. I'll update to the PR now!

https://github.com/elixir-lang/elixir/issues/5236

**Comment by mustafaturan** [comment]
Thanks, merged your PR to master

**Comment by ShaneWilton** [comment]
I'll do that one tomorrow :)
