### ISSUE TITLE
Rename all `micro_services`, `micro_service` and `microservices` as `microservice` 

### ISSUE THREAD

**Issue by mustafaturan** [otobus/event_bus#54]
To standardize, and follow Erlang 19+ consistency rename all `micro_services`, `micro_service` and `microservices` time unit occurrences to  `microservice` 

**Occurences:**
https://github.com/otobus/event_bus/search?q=micro_seconds&unscoped_q=micro_seconds
https://github.com/otobus/event_bus/search?q=microseconds&unscoped_q=microseconds

**Ref:** https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/system.ex#L65

//cc @ShaneWilton

**Comment by ShaneWilton** [comment]
To clarify, you mean to rename `:micro_seconds` to `:microsecond`, right? Not `:micro_service`?

**Comment by mustafaturan** [comment]
Thanks for your time 👏 
I will bump the minor version today
