### ISSUE TITLE
Small tweaks to Creating Event Consumers wiki page

### ISSUE THREAD

**Issue by jutonz** [otobus/event_bus#67]
I made some small tweaks to the `Creating Event Consumers` wiki page (just small language changes and an indentation fix), but since GitHub doesn't allow pull requests to the wiki I'm making an issue instead.

I cloned the wiki and made the changes in that fork. You can see the new version [here](https://github.com/jutonz/event_bus-wiki/blob/master/Creating-Event-Consumers.md), and a diff of changes [here](https://github.com/jutonz/event_bus-wiki/commit/cfcad5bb782e6745a31ac72c2cd636440dfc8a6f).

If there's a better way you'd like these changes presented I can definitely do something else.

Thanks!

**Comment by mustafaturan** [comment]
👍

I think this is the only way for now. I will update this evening, thanks ✅

**Comment by mustafaturan** [comment]
Thanks again, applied changes https://github.com/otobus/event_bus/wiki/Creating-Event-Consumers/187f8a930a7ebaebe1547da2a1e5a6022436a013
