### ISSUE TITLE
Multiple nodes

### ISSUE THREAD

**Issue by joshnuss** [otobus/event_bus#80]
Hi!

Wondering if it's possible to run one `event_bus` across multiple nodes? Since it uses ETS?
It wasn't obvious to me, if you have any pointers I'd be happy to create a demo app or update the documentation.

Thanks for creating this project! It is super cool and easy to read :ok_hand:

**Comment by mustafaturan** [comment]
Hi 👋 I think this one adressed in one of the previous questions. But here is a link https://github.com/otobus/event_bus/issues/76#issuecomment-430465882
